version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: deadmansswitch_postgres
    restart: unless-stopped
    # Remove external port exposure for production security
    # ports:
    #   - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: deadmansswitch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Mount SSL certificates for production
      - ./ssl-certs/server.crt:/var/lib/postgresql/server.crt:ro
      - ./ssl-certs/server.key:/var/lib/postgresql/server.key:ro
      - ./ssl-certs/ca.crt:/var/lib/postgresql/ca.crt:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c ssl_ca_file=/var/lib/postgresql/ca.crt
      -c shared_preload_libraries=pgcrypto
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: deadmansswitch_redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
