# Self-hosted email server using docker-mailserver
# This provides a complete email solution without third-party dependencies
version: "3.8"

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.${DOMAIN:-deadmansswitch.local}
    ports:
      - "25:25" # SMTP
      - "143:143" # IMAP
      - "465:465" # SMTPS
      - "587:587" # MSA
      - "993:993" # IMAPS
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Basic configuration
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ENABLE_MANAGESIEVE=1
      - ONE_DIR=1
      - ENABLE_UPDATE_CHECK=1
      - UPDATE_CHECK_INTERVAL=1d
      - PERMIT_DOCKER=connected-networks

      # SSL/TLS configuration
      - SSL_TYPE=letsencrypt
      - ENABLE_SSL=1
      - SSL_CERT_PATH=/etc/letsencrypt/live/${DOMAIN:-deadmansswitch.local}/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/${DOMAIN:-deadmansswitch.local}/privkey.pem

      # SMTP Authentication
      - ENABLE_SASLAUTHD=0
      - SMTP_ONLY=0

      # Anti-spam and security
      - SPOOF_PROTECTION=1
      - ENABLE_SRS=1
      - DEFAULT_RELAY_HOST=

      # Dovecot configuration
      - ENABLE_IMAP=1
      - ENABLE_POP3=0
      - DOVECOT_MAILBOX_FORMAT=maildir
      - DOVECOT_TLS=yes

      # Postfix configuration
      - POSTFIX_DAGENT=dovecot
      - POSTFIX_MAILBOX_SIZE_LIMIT=0
      - POSTFIX_MESSAGE_SIZE_LIMIT=100000000

      # Log level
      - LOG_LEVEL=info
      - SUPERVISOR_LOGLEVEL=warn

    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss -lntp | grep -E ':25|:143|:465|:587|:993' || exit 1"
      timeout: 45s
      interval: 30s
      retries: 3
    networks:
      - mailserver-network

  # Optional: Webmail interface
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    depends_on:
      - mailserver
      - roundcube-db
    ports:
      - "8080:80"
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=roundcube-db
      - ROUNDCUBEMAIL_DB_PORT=5432
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=${ROUNDCUBE_DB_PASSWORD:-roundcube_password}
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mailserver
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
    volumes:
      - ./docker-data/roundcube/www:/var/www/html
      - ./docker-data/roundcube/config:/var/roundcube/config
    restart: always
    networks:
      - mailserver-network

  # Database for Roundcube
  roundcube-db:
    image: postgres:15-alpine
    container_name: roundcube-db
    environment:
      - POSTGRES_DB=roundcube
      - POSTGRES_USER=roundcube
      - POSTGRES_PASSWORD=${ROUNDCUBE_DB_PASSWORD:-roundcube_password}
    volumes:
      - ./docker-data/roundcube/db:/var/lib/postgresql/data
    restart: always
    networks:
      - mailserver-network

networks:
  mailserver-network:
    driver: bridge

# Volumes for persistent data
volumes:
  mail-data:
  mail-state:
  mail-logs:
  roundcube-www:
  roundcube-config:
  roundcube-db:
